<?php
/**
 * @file Add .epub and .ibooks extensions/mimetypes to Drupal
 */


/**
 * Implements hook_file_mimetype_mapping_alter().
 *
 * Add the relevant mimetypes and extensions for `.epub' and `.ibooks' files.
 *
 * Based on example code in
 * https://api.drupal.org/comment/22373#comment-22373 .
 */
function ox_mimetypes_file_mimetype_mapping_alter(&$mapping) {
  // Add support for epubs
  $new_mappings['epub'] = 'application/epub+zip';
  $new_mappings['ibooks'] = 'application/x-ibooks+zip';

  foreach ($new_mappings as $extension => $mime_type) {
    if (!in_array($mime_type, $mapping['mimetypes'])) {
      // If the mime type does not already exist, add it.
      $mapping['mimetypes'][] = $mime_type;
    }

    // Get the index of the mime type and assign the extension to that key.
    $index = array_search($mime_type, $mapping['mimetypes']);
    $mapping['extensions'][$extension] = $index;
  }
}
